### ISSUE TITLE
Add bs4 and other packages as dependencies for installation

### ISSUE THREAD

**Issue by bencomp** [manuzhang/mkdocs-htmlproofer-plugin#1]
After initial installation and configuration, I couldn't start mkdocs because BeautifulSoup wasn't available. Looking at the code, it looks like `requests` is also an external dependency.

**Comment by manuzhang** [comment]
Thanks, added in https://github.com/manuzhang/mkdocs-htmlproofer-plugin/commit/39ab7ad0bb600a5a6bc856c6755d9ac921925d90
