### ISSUE TITLE
Link not correctly taken over by plugin

### ISSUE THREAD

**Issue by kkwekkeboom** [manuzhang/mkdocs-htmlproofer-plugin#24]
I have an issue with links incorrectly marked as not found. To reproduce the issue I created an empty project with just two files and the following structure
```
docs/page1.md
docs/directory1/page2.md
```

page1.md 
``` 
## Section One
```

page2.md
```
[thelink](../page1.md#section-2)
```

The link in page2 is incorrectly regarded as not existing 
```
Warning: Unable to locate Markdown source file for: ../page1/
ERROR    -  Error building page 'directory1/page2.md':
ERROR    -  ../../page1/#section1: 404
```

It seems to append an extra `../` to the link.

**Comment by manuzhang** [comment]
@johnthagen could you help to take a look ?

**Comment by johnthagen** [comment]
Yes, please assign this issue to me.

**Comment by johnthagen** [comment]
@kkwekkeboom Could you please provide:

- Operating System
- Python Version
- Output of `pip list`
- Contents of `mkdocs.yml`

**Comment by kkwekkeboom** [comment]
5.8.0-63-generic #71~20.04.1-Ubuntu
python 3.8.10

requirements.txt
```
mkdocs-material==6.0.2
mkdocs-minify-plugin==0.3.0
pymdown-extensions==8.0
mkdocs-htmlproofer-plugin==0.5.0
```

mkdocs.yaml
```
site_name: test
site_dir: build

plugins:
  - search
  - minify:
      minify_html: true
  - htmlproofer:
      raise_error: True
```

**Comment by johnthagen** [comment]
@kkwekkeboom Not saying there aren't other problems, but your anchor link you show in the example *is* actually incorrect:

```md
[thelink](../page1.md#section-2)
```

Per your example, this should be:

```md
[thelink](../page1.md#section-one)
```

**Comment by johnthagen** [comment]
Reproduced error here: https://github.com/johnthagen/-mkdocs-htmlproofer-plugin-test

**Comment by johnthagen** [comment]
@manuzhang Could you release 0.6.0 with this fix?
