### ISSUE TITLE
Remove lxml dependency

### ISSUE THREAD

**Issue by johnthagen** [manuzhang/mkdocs-htmlproofer-plugin#34]
BeautifulSoup supports multiple XML parsers:

- https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser

Currently, `mkdocs-htmlproofer-plugin` depends on `lxml`:

https://github.com/manuzhang/mkdocs-htmlproofer-plugin/blob/40d070b0fefc8d1fdd406245cd02ed1c508f1c1a/setup.py#L27

https://github.com/manuzhang/mkdocs-htmlproofer-plugin/blob/2573d34f4ffd35076feb9a7a6fc4b1743061fe19/htmlproofer/plugin.py#L69

This has the advantage that HTML parsing can be a bit faster than Python's `html.parser`, but this comes at the cost of an extra dependency. We've observed issues in the past with `lxml` as a dependency (since it contains C code that must be published as a wheel or compiled from source).

Currently, there is an issue that the latest release of `lxml` cannot be installed on any Mac system due to missing published wheels. Pinning to an older version of `lxml` is not ideal, because older versions contain a CVE.

- https://bugs.launchpad.net/lxml/+bug/1980575

I would recommend that `mkdocs-htmlproofer-plugin` switch to Python's stdlib parser, which has adequate performance and would simplify maintenance and usage of this project:

```py
BeautifulSoup(markup, "html.parser")
```

I'm happy to open a PR for this if this is acceptable.

**Comment by manuzhang** [comment]
Good idea! Please go ahead to open a PR. Thank you.
