### ISSUE TITLE
Wheel missing from PyPI for 0.10.0 release

### ISSUE THREAD

**Issue by johnthagen** [manuzhang/mkdocs-htmlproofer-plugin#39]
See: https://pypi.org/project/mkdocs-htmlproofer-plugin/0.10.0/#files

There is no `.whl` file published. 

See https://pythonwheels.com/ for the reasons publishing a wheel is important.

The `bdist_wheel` part of the `publish.sh` script should have made the wheel automatically:

https://github.com/manuzhang/mkdocs-htmlproofer-plugin/blob/49593db56e70148e48e04042d04d60075eda908c/publish.sh#L4

Perhaps you ran the steps manually rather than using the script?

**Comment by manuzhang** [comment]
@johnthagen thanks, I forgot my own script. It's fixed now.
