### ISSUE TITLE
mailto: links generate 404 errors

### ISSUE THREAD

**Issue by es-fabricemarie** [manuzhang/mkdocs-htmlproofer-plugin#54]
If the document contains mailto: links the plugin returns 404 for each of them.

**To Reproduce**
create a mailto: link (for example `mailto:toto@toto.com`) in a source .md file and build your documentation.

It should simply ignore mailto links.

**Comment by manuzhang** [comment]
@es-fabricemarie Thanks for report. Would you mind submitting a PR?

**Comment by kolibri91** [comment]
> Would it be valid to consider each URL with a protocol `<protocol>:...` as an external one?

Considering wikipedia, I would say yes.
An URL would have an "scheme" except it is relative (in our terms: internal).

* https://en.wikipedia.org/wiki/URL#Syntax
* https://en.wikipedia.org/wiki/URL#Protocol-relative_URLs

**Comment by johnthagen** [comment]
Should we simply skip any links that don't start with `http`?

**Comment by johnthagen** [comment]
@kolibri91 Right good point. I meant skipping any external URLs that don't start with `http`.

**Comment by kolibri91** [comment]
I would have an idea in mind how to solve it in a generic way. I will preserve the existing behavior expect of replacing checks of "unknown" schemes by a info message.

Please give me some tine to prepare the PR.

**Comment by manuzhang** [comment]
Sorry, I don't have time to look into this. Have you checked how https://github.com/gjtorikian/html-proofer handle it?

**Comment by kolibri91** [comment]
> Sorry, I don't have time to look into this. Have you checked how https://github.com/gjtorikian/html-proofer handle it?

Looks that they use a "ignore": https://github.com/gjtorikian/html-proofer/issues/754

Anyhow, I will have time soon to open the PR. Looking forward to it 😃
