### ISSUE TITLE
Does it work with internal URLs ?

### ISSUE THREAD

**Issue by majkinetor** [manuzhang/mkdocs-htmlproofer-plugin#6]
I often move md pages around and links then stop working. Does this plugin catch that ? Internal and relative URLs.

Didn't try it yet but glanced into code and it looke like it doesn't do that ?

**Comment by manuzhang** [comment]
I think mkDocs already validates internal links when transforming them.

**Comment by majkinetor** [comment]
No it doesn't

**Comment by manuzhang** [comment]
I see. The project looks great.

**Comment by majkinetor** [comment]
I finally finished using external tool blc. 
Here is the output for someone that might have the same problem: 
* https://ci.appveyor.com/project/majkinetor/mm-docs-template#L178
