### ISSUE TITLE
Handle python 3.6 with mkdocs < 1.4

### ISSUE THREAD

**Issue by kolibri91** [manuzhang/mkdocs-htmlproofer-plugin#60]
In my opinion Python 3.6 is end of life and we should simply drop it from the test suite. Even Python 3.7 is almost end of life (2 months).

- https://endoflife.date/python

_Originally posted by @johnthagen in https://github.com/manuzhang/mkdocs-htmlproofer-plugin/issues/59#issuecomment-1505638073_

**Comment by kolibri91** [comment]
Additionally, there is a bug in `mkdocs<1.4`. Changes to the `mkdocs.config.Config`-class are persistent over multiple test runs.
It's not dramatically but I was surprised.

**Comment by johnthagen** [comment]
I would recommend that we:

- Drop support for Python 3.6, which is End of Life
- Set the MkDocs minimum requirement to `mkdocs>=1.4.0`, which is 9 months or so old and seems like a reasonable bump up to reduce the likelihood of users using a very old version of MkDocs that we aren't testing against.
