### ISSUE TITLE
raise_error_excludes change

### ISSUE THREAD

**Issue by SeanTAllen** [manuzhang/mkdocs-htmlproofer-plugin#69]
I'm opening this issue to discuss a change/enhancement to `raise_error_excludes`.

When using htmlproofer, I've found the need to exclude entire error ranges by host. I was expecting that something like:

429: ["https://github.com"] to exclude any rate limiting for any URL from GitHub. Given that htmlproofer often triggers rate limiting for me, I was hoping that this would work like...

"pattern" in "url" where the standard python string in string checking would be done so that it would be:

"https://github.com" in "https://github.com/some-specific-url" is true.

This isn't how it is implemented and thinking about it, that is a touch limited. I would like to be able to do something like that though. Perhaps via the method above, perhaps a regex check on each element of the "status code" dictionary?

**Comment by manuzhang** [comment]
have you tried https://github.com/manuzhang/mkdocs-htmlproofer-plugin?tab=readme-ov-file#ignore_urls?

**Comment by SeanTAllen** [comment]
I don't want to ignore the urls. I want to check them. 404 would be an error. 429 wouldn't. As an example.
