### ISSUE TITLE
Add option to prevent downloading the entirety of a file

### ISSUE THREAD

**Issue by benjamb** [manuzhang/mkdocs-htmlproofer-plugin#76]
In one of our projects, we include various links to the latest binary release artefacts of our project within the documentation, as well as many links to other fairly large binaries. This can lead to the plugin bringing total `mkdocs build` time to 15+ minutes.

To validate a URL, you needn't download the entire file, just a few bytes will do. It would be great if a configuration parameter were added that limited the download to the first N bytes of a file.

I implemented the following quick hack locally to see the how much difference it would make:
```diff
diff --git a/htmlproofer/plugin.py b/htmlproofer/plugin.py
index 59d62fa..3f98e87 100644
--- a/htmlproofer/plugin.py
+++ b/htmlproofer/plugin.py
@@ -146,7 +146,8 @@ class HtmlProoferPlugin(BasePlugin):
     @lru_cache(maxsize=1000)
     def resolve_web_scheme(self, url: str) -> int:
         try:
-            response = self._session.get(url, timeout=URL_TIMEOUT)
+            headers = {"Range": "bytes=0-100"}
+            response = self._session.get(url, timeout=URL_TIMEOUT, headers=headers)
             return response.status_code
         except requests.exceptions.Timeout:
             return 504
```
The build time went from:
```
INFO    -  Documentation built in 982.92 seconds
```
to:
```
INFO    -  Documentation built in 39.47 seconds
```

**Comment by benjamb** [comment]
@manuzhang Sure thing. I'll try to get something drafted by today.

**Comment by SeanTAllen** [comment]
FYI, I decided to see what the impact would be of using `HEAD` instead of `GET` for requests. It would in theory, make it so this doesn't need to be configured and everyone using could benefit. Unfortunately, a small percentage of the sites came back that they didn't support HEAD requests. So, this approach using a GET that only grabs a small number of bytes is less likely to encounter issues.

**Comment by benjamb** [comment]
The project had used `HEAD` historically, but that was changed to `GET` requests last year: 50c44f2d57a8c03d02c0c505ec663a92beeb89bf

What was the behaviour with sites that didn't support `HEAD`? I prefer the idea of using `HEAD` by default, but falling back to `GET`, however I also don't really want to break the behaviour that users have come to expect since that change.

**Comment by SeanTAllen** [comment]
They returned a method not supported status code.
