### ISSUE TITLE
Regression with mkdocs-material blog posts support

### ISSUE THREAD

**Issue by SeanTAllen** [manuzhang/mkdocs-htmlproofer-plugin#83]
Prior to the 1.2.1 release, relative blog links such as `/blog/posts/last-week-in-pony-011424.md#openssl-3-2-related-bug` correctly proofed.

As of 1.2.1, it now returns as a 404.

@manuzhang @ben-foxmoore 

I'm guessing this is related to https://github.com/manuzhang/mkdocs-htmlproofer-plugin/pull/80

**Comment by manuzhang** [comment]
@SeanTAllen I'll look into it later today. Please downgrade to 1.2.0 for now

**Comment by manuzhang** [comment]
Not sure why `/blog/posts/last-week-in-pony-022524.md#office-hours` from https://github.com/ponylang/ponylang-website/blob/main/docs/blog/posts/last-week-in-pony-030324.md is not reported as 404.

**Comment by manuzhang** [comment]
ok, the issue is how `3.2` in the heading is slugified in the link. The markdown library slugifies `OpenSSL 3.2 related bug` to  `#openssl-32-related-bug`.

**Comment by manuzhang** [comment]
@SeanTAllen This is not a regression. The issue was not caught before #80.

I tested with https://facelessuser.github.io/pymdown-extensions/extras/slugs/ but it gave the same result as `markdown.extensions.toc.slugify`

```python
>>> import pymdownx.slugs
>>> slugs.slugify(case='lower')('OpenSSL 3.2 related bug','-')
'openssl-32-related-bug'
```

Do you know any specific version or configuration that slugifies it to `openssl-3-2-related-bug`?

**Comment by SeanTAllen** [comment]
User error when I clicked. Disregard. Sorry.

**Comment by manuzhang** [comment]
Do you mean this anchor `/blog/posts/last-week-in-pony-011424.md#openssl-3-2-related-bug` is not correct?

**Comment by SeanTAllen** [comment]
Yeah. I incorrectly thought it was a valid link. No regression related to it

**Comment by manuzhang** [comment]
Thanks for reporting anyway.
